# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AutomationGUI_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 762)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 480))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/karmaIcon"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QToolButton {\n"
"    margin: 4px;\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QToolBar {\n"
"    spacing: 16px;\n"
"    margin: 2px;\n"
"    background-color: rgb(255, 170, 0);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QMenu::separator {\n"
"    height: 1px;\n"
"    background: rgb(255, 170, 0);\n"
"}")
        MainWindow.setIconSize(QtCore.QSize(32, 32))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("QPushButton, QToolButton {\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 170, 0);\n"
"}")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(24, 24))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.generalLayout = QtWidgets.QGridLayout()
        self.generalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.generalLayout.setContentsMargins(0, 0, 0, 0)
        self.generalLayout.setHorizontalSpacing(5)
        self.generalLayout.setVerticalSpacing(8)
        self.generalLayout.setObjectName("generalLayout")
        self.testCaseExcelLabel_2 = QtWidgets.QLabel(self.tab)
        self.testCaseExcelLabel_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.testCaseExcelLabel_2.setObjectName("testCaseExcelLabel_2")
        self.generalLayout.addWidget(self.testCaseExcelLabel_2, 0, 0, 1, 1)
        self.browseVariablePoolBtn = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browseVariablePoolBtn.sizePolicy().hasHeightForWidth())
        self.browseVariablePoolBtn.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/copy"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.browseVariablePoolBtn.setIcon(icon1)
        self.browseVariablePoolBtn.setIconSize(QtCore.QSize(24, 24))
        self.browseVariablePoolBtn.setObjectName("browseVariablePoolBtn")
        self.generalLayout.addWidget(self.browseVariablePoolBtn, 3, 2, 1, 1)
        self.browseCsvReportBtn = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browseCsvReportBtn.sizePolicy().hasHeightForWidth())
        self.browseCsvReportBtn.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/folderOpen"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.browseCsvReportBtn.setIcon(icon2)
        self.browseCsvReportBtn.setIconSize(QtCore.QSize(24, 24))
        self.browseCsvReportBtn.setObjectName("browseCsvReportBtn")
        self.generalLayout.addWidget(self.browseCsvReportBtn, 1, 2, 1, 1)
        self.csvReportFolderToolButton = QtWidgets.QToolButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.csvReportFolderToolButton.sizePolicy().hasHeightForWidth())
        self.csvReportFolderToolButton.setSizePolicy(sizePolicy)
        self.csvReportFolderToolButton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.csvReportFolderToolButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/menu"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.csvReportFolderToolButton.setIcon(icon3)
        self.csvReportFolderToolButton.setIconSize(QtCore.QSize(24, 24))
        self.csvReportFolderToolButton.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.csvReportFolderToolButton.setAutoRaise(False)
        self.csvReportFolderToolButton.setArrowType(QtCore.Qt.NoArrow)
        self.csvReportFolderToolButton.setObjectName("csvReportFolderToolButton")
        self.generalLayout.addWidget(self.csvReportFolderToolButton, 1, 3, 1, 1)
        self.variablePoolLabel = QtWidgets.QLabel(self.tab)
        self.variablePoolLabel.setObjectName("variablePoolLabel")
        self.generalLayout.addWidget(self.variablePoolLabel, 3, 0, 1, 1)
        self.csvReportEdit = QtWidgets.QLineEdit(self.tab)
        self.csvReportEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.csvReportEdit.setClearButtonEnabled(False)
        self.csvReportEdit.setObjectName("csvReportEdit")
        self.generalLayout.addWidget(self.csvReportEdit, 1, 1, 1, 1)
        self.csvReportLabel = QtWidgets.QLabel(self.tab)
        self.csvReportLabel.setObjectName("csvReportLabel")
        self.generalLayout.addWidget(self.csvReportLabel, 1, 0, 1, 1)
        self.variablePoolEdit = QtWidgets.QLineEdit(self.tab)
        self.variablePoolEdit.setObjectName("variablePoolEdit")
        self.generalLayout.addWidget(self.variablePoolEdit, 3, 1, 1, 1)
        self.polarionExcelEdit = QtWidgets.QLineEdit(self.tab)
        self.polarionExcelEdit.setObjectName("polarionExcelEdit")
        self.generalLayout.addWidget(self.polarionExcelEdit, 0, 1, 1, 1)
        self.variablePoolToolButton = QtWidgets.QToolButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.variablePoolToolButton.sizePolicy().hasHeightForWidth())
        self.variablePoolToolButton.setSizePolicy(sizePolicy)
        self.variablePoolToolButton.setText("")
        self.variablePoolToolButton.setIcon(icon3)
        self.variablePoolToolButton.setIconSize(QtCore.QSize(24, 24))
        self.variablePoolToolButton.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.variablePoolToolButton.setObjectName("variablePoolToolButton")
        self.generalLayout.addWidget(self.variablePoolToolButton, 3, 3, 1, 1)
        self.polarionExcelToolButton = QtWidgets.QToolButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.polarionExcelToolButton.sizePolicy().hasHeightForWidth())
        self.polarionExcelToolButton.setSizePolicy(sizePolicy)
        self.polarionExcelToolButton.setText("")
        self.polarionExcelToolButton.setIcon(icon3)
        self.polarionExcelToolButton.setIconSize(QtCore.QSize(24, 24))
        self.polarionExcelToolButton.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.polarionExcelToolButton.setAutoRaise(False)
        self.polarionExcelToolButton.setObjectName("polarionExcelToolButton")
        self.generalLayout.addWidget(self.polarionExcelToolButton, 0, 3, 1, 1)
        self.browsePolarionExcelBtn = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browsePolarionExcelBtn.sizePolicy().hasHeightForWidth())
        self.browsePolarionExcelBtn.setSizePolicy(sizePolicy)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/excel"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.browsePolarionExcelBtn.setIcon(icon4)
        self.browsePolarionExcelBtn.setIconSize(QtCore.QSize(24, 24))
        self.browsePolarionExcelBtn.setObjectName("browsePolarionExcelBtn")
        self.generalLayout.addWidget(self.browsePolarionExcelBtn, 0, 2, 1, 1)
        self.verticalLayout_13.addLayout(self.generalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.updateVariablePoolCheckBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.updateVariablePoolCheckBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.updateVariablePoolCheckBox.setObjectName("updateVariablePoolCheckBox")
        self.verticalLayout_7.addWidget(self.updateVariablePoolCheckBox)
        self.autorunCheckBox = QtWidgets.QCheckBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.autorunCheckBox.sizePolicy().hasHeightForWidth())
        self.autorunCheckBox.setSizePolicy(sizePolicy)
        self.autorunCheckBox.setChecked(False)
        self.autorunCheckBox.setObjectName("autorunCheckBox")
        self.verticalLayout_7.addWidget(self.autorunCheckBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.horizontalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.versionCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.versionCheckBox.sizePolicy().hasHeightForWidth())
        self.versionCheckBox.setSizePolicy(sizePolicy)
        self.versionCheckBox.setObjectName("versionCheckBox")
        self.verticalLayout_12.addWidget(self.versionCheckBox)
        self.callFunctionDebugCheckbox = QtWidgets.QCheckBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.callFunctionDebugCheckbox.sizePolicy().hasHeightForWidth())
        self.callFunctionDebugCheckbox.setSizePolicy(sizePolicy)
        self.callFunctionDebugCheckbox.setObjectName("callFunctionDebugCheckbox")
        self.verticalLayout_12.addWidget(self.callFunctionDebugCheckbox)
        self.dtcExCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtcExCheckBox.sizePolicy().hasHeightForWidth())
        self.dtcExCheckBox.setSizePolicy(sizePolicy)
        self.dtcExCheckBox.setObjectName("dtcExCheckBox")
        self.verticalLayout_12.addWidget(self.dtcExCheckBox)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(0, 10, 0, 10)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pauseCheckbox = QtWidgets.QCheckBox(self.groupBox_4)
        self.pauseCheckbox.setObjectName("pauseCheckbox")
        self.horizontalLayout_8.addWidget(self.pauseCheckbox)
        self.pauseStepSpinbox = QtWidgets.QSpinBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pauseStepSpinbox.setFont(font)
        self.pauseStepSpinbox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pauseStepSpinbox.setSuffix("")
        self.pauseStepSpinbox.setMinimum(1)
        self.pauseStepSpinbox.setMaximum(9999)
        self.pauseStepSpinbox.setProperty("value", 1)
        self.pauseStepSpinbox.setObjectName("pauseStepSpinbox")
        self.horizontalLayout_8.addWidget(self.pauseStepSpinbox)
        self.verticalLayout_12.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, 10, -1, 10)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.printStepsInOutputCheckbox = QtWidgets.QCheckBox(self.groupBox_4)
        self.printStepsInOutputCheckbox.setObjectName("printStepsInOutputCheckbox")
        self.horizontalLayout_9.addWidget(self.printStepsInOutputCheckbox)
        self.maxPrintsInOutputSpinbox = QtWidgets.QSpinBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.maxPrintsInOutputSpinbox.setFont(font)
        self.maxPrintsInOutputSpinbox.setMinimum(1)
        self.maxPrintsInOutputSpinbox.setObjectName("maxPrintsInOutputSpinbox")
        self.horizontalLayout_9.addWidget(self.maxPrintsInOutputSpinbox)
        self.verticalLayout_12.addLayout(self.horizontalLayout_9)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem1)
        self.horizontalLayout_2.addWidget(self.groupBox_4)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.versionTableView = QtWidgets.QTableView(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.versionTableView.sizePolicy().hasHeightForWidth())
        self.versionTableView.setSizePolicy(sizePolicy)
        self.versionTableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.versionTableView.setObjectName("versionTableView")
        self.verticalLayout_9.addWidget(self.versionTableView)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.versionAddButton = QtWidgets.QPushButton(self.groupBox_2)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/add"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.versionAddButton.setIcon(icon5)
        self.versionAddButton.setObjectName("versionAddButton")
        self.horizontalLayout_6.addWidget(self.versionAddButton)
        self.versionRemoveButton = QtWidgets.QPushButton(self.groupBox_2)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/remove"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.versionRemoveButton.setIcon(icon6)
        self.versionRemoveButton.setObjectName("versionRemoveButton")
        self.horizontalLayout_6.addWidget(self.versionRemoveButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.verticalLayout_13.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem3)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon_white/tune"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon7, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.loggingTabLayout = QtWidgets.QHBoxLayout()
        self.loggingTabLayout.setObjectName("loggingTabLayout")
        self.logmodeLayout = QtWidgets.QVBoxLayout()
        self.logmodeLayout.setObjectName("logmodeLayout")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.logRadioBtn0 = QtWidgets.QRadioButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logRadioBtn0.sizePolicy().hasHeightForWidth())
        self.logRadioBtn0.setSizePolicy(sizePolicy)
        self.logRadioBtn0.setObjectName("logRadioBtn0")
        self.verticalLayout_4.addWidget(self.logRadioBtn0)
        self.logRadioBtn1 = QtWidgets.QRadioButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logRadioBtn1.sizePolicy().hasHeightForWidth())
        self.logRadioBtn1.setSizePolicy(sizePolicy)
        self.logRadioBtn1.setObjectName("logRadioBtn1")
        self.verticalLayout_4.addWidget(self.logRadioBtn1)
        self.logRadioBtn2 = QtWidgets.QRadioButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logRadioBtn2.sizePolicy().hasHeightForWidth())
        self.logRadioBtn2.setSizePolicy(sizePolicy)
        self.logRadioBtn2.setObjectName("logRadioBtn2")
        self.verticalLayout_4.addWidget(self.logRadioBtn2)
        self.logmodeLayout.addWidget(self.groupBox)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.logmodeLayout.addItem(spacerItem4)
        self.loggingTabLayout.addLayout(self.logmodeLayout)
        self.addSignalGroupBox = QtWidgets.QGroupBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addSignalGroupBox.sizePolicy().hasHeightForWidth())
        self.addSignalGroupBox.setSizePolicy(sizePolicy)
        self.addSignalGroupBox.setObjectName("addSignalGroupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.addSignalGroupBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.addSignalListView = QtWidgets.QListView(self.addSignalGroupBox)
        self.addSignalListView.setEnabled(True)
        self.addSignalListView.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.addSignalListView.setObjectName("addSignalListView")
        self.verticalLayout_5.addWidget(self.addSignalListView)
        self.addSignalEdit = QtWidgets.QLineEdit(self.addSignalGroupBox)
        self.addSignalEdit.setObjectName("addSignalEdit")
        self.verticalLayout_5.addWidget(self.addSignalEdit)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.addSignalBtn = QtWidgets.QPushButton(self.addSignalGroupBox)
        self.addSignalBtn.setIcon(icon5)
        self.addSignalBtn.setObjectName("addSignalBtn")
        self.verticalLayout.addWidget(self.addSignalBtn)
        self.removeSignalBtn = QtWidgets.QPushButton(self.addSignalGroupBox)
        self.removeSignalBtn.setIcon(icon6)
        self.removeSignalBtn.setObjectName("removeSignalBtn")
        self.verticalLayout.addWidget(self.removeSignalBtn)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.loggingTabLayout.addWidget(self.addSignalGroupBox)
        self.verticalLayout_10.addLayout(self.loggingTabLayout)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icon_white/eventNote"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2, icon8, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.dtcTabLayout = QtWidgets.QVBoxLayout()
        self.dtcTabLayout.setObjectName("dtcTabLayout")
        self.dtcExGroupBox = QtWidgets.QGroupBox(self.tab_3)
        self.dtcExGroupBox.setObjectName("dtcExGroupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.dtcExGroupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.dtcTableView = QtWidgets.QTableView(self.dtcExGroupBox)
        self.dtcTableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.dtcTableView.setObjectName("dtcTableView")
        self.verticalLayout_6.addWidget(self.dtcTableView)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.addDtcExEdit = QtWidgets.QLineEdit(self.dtcExGroupBox)
        self.addDtcExEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.addDtcExEdit.setInputMask("")
        self.addDtcExEdit.setClearButtonEnabled(False)
        self.addDtcExEdit.setObjectName("addDtcExEdit")
        self.verticalLayout_2.addWidget(self.addDtcExEdit)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.addDtcExBtn = QtWidgets.QPushButton(self.dtcExGroupBox)
        self.addDtcExBtn.setIcon(icon5)
        self.addDtcExBtn.setObjectName("addDtcExBtn")
        self.horizontalLayout_15.addWidget(self.addDtcExBtn)
        self.removeDtcExBtn = QtWidgets.QPushButton(self.dtcExGroupBox)
        self.removeDtcExBtn.setIcon(icon6)
        self.removeDtcExBtn.setObjectName("removeDtcExBtn")
        self.horizontalLayout_15.addWidget(self.removeDtcExBtn)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        self.dtcTabLayout.addWidget(self.dtcExGroupBox)
        self.horizontalLayout_11.addLayout(self.dtcTabLayout)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icon_white/code"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_3, icon9, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setStyleSheet("")
        self.tab_6.setObjectName("tab_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.polarionToolbarLayout = QtWidgets.QVBoxLayout()
        self.polarionToolbarLayout.setObjectName("polarionToolbarLayout")
        self.polarionReadExcelButton = QtWidgets.QToolButton(self.tab_6)
        self.polarionReadExcelButton.setIcon(icon4)
        self.polarionReadExcelButton.setIconSize(QtCore.QSize(24, 24))
        self.polarionReadExcelButton.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.polarionReadExcelButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.polarionReadExcelButton.setObjectName("polarionReadExcelButton")
        self.polarionToolbarLayout.addWidget(self.polarionReadExcelButton)
        self.polarionSaveExcelButton = QtWidgets.QToolButton(self.tab_6)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icon/save"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.polarionSaveExcelButton.setIcon(icon10)
        self.polarionSaveExcelButton.setIconSize(QtCore.QSize(24, 24))
        self.polarionSaveExcelButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.polarionSaveExcelButton.setObjectName("polarionSaveExcelButton")
        self.polarionToolbarLayout.addWidget(self.polarionSaveExcelButton)
        self.polarionUpdatePassedButton = QtWidgets.QToolButton(self.tab_6)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icon/verdictPassed"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.polarionUpdatePassedButton.setIcon(icon11)
        self.polarionUpdatePassedButton.setIconSize(QtCore.QSize(24, 24))
        self.polarionUpdatePassedButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.polarionUpdatePassedButton.setObjectName("polarionUpdatePassedButton")
        self.polarionToolbarLayout.addWidget(self.polarionUpdatePassedButton)
        self.polarionUpdateAllButton = QtWidgets.QToolButton(self.tab_6)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icon/verdictAll"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.polarionUpdateAllButton.setIcon(icon12)
        self.polarionUpdateAllButton.setIconSize(QtCore.QSize(24, 24))
        self.polarionUpdateAllButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.polarionUpdateAllButton.setObjectName("polarionUpdateAllButton")
        self.polarionToolbarLayout.addWidget(self.polarionUpdateAllButton)
        self.polarionUpdateRevisionButton = QtWidgets.QToolButton(self.tab_6)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icon/history"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.polarionUpdateRevisionButton.setIcon(icon13)
        self.polarionUpdateRevisionButton.setIconSize(QtCore.QSize(24, 24))
        self.polarionUpdateRevisionButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.polarionUpdateRevisionButton.setObjectName("polarionUpdateRevisionButton")
        self.polarionToolbarLayout.addWidget(self.polarionUpdateRevisionButton)
        self.updateStepsButton = QtWidgets.QToolButton(self.tab_6)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icon/numberedList"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.updateStepsButton.setIcon(icon14)
        self.updateStepsButton.setIconSize(QtCore.QSize(24, 24))
        self.updateStepsButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.updateStepsButton.setObjectName("updateStepsButton")
        self.polarionToolbarLayout.addWidget(self.updateStepsButton)
        self.updateHyperlinksButton = QtWidgets.QToolButton(self.tab_6)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icon/link"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.updateHyperlinksButton.setIcon(icon15)
        self.updateHyperlinksButton.setIconSize(QtCore.QSize(24, 24))
        self.updateHyperlinksButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.updateHyperlinksButton.setObjectName("updateHyperlinksButton")
        self.polarionToolbarLayout.addWidget(self.updateHyperlinksButton)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.polarionToolbarLayout.addItem(spacerItem7)
        self.horizontalLayout.addLayout(self.polarionToolbarLayout)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.titleEdit = QtWidgets.QLineEdit(self.tab_6)
        self.titleEdit.setEnabled(True)
        self.titleEdit.setAutoFillBackground(False)
        self.titleEdit.setInputMask("")
        self.titleEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.titleEdit.setClearButtonEnabled(False)
        self.titleEdit.setObjectName("titleEdit")
        self.verticalLayout_8.addWidget(self.titleEdit)
        self.descriptionEdit = QtWidgets.QLineEdit(self.tab_6)
        self.descriptionEdit.setEnabled(True)
        self.descriptionEdit.setObjectName("descriptionEdit")
        self.verticalLayout_8.addWidget(self.descriptionEdit)
        self.splitter = QtWidgets.QSplitter(self.tab_6)
        self.splitter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.splitter.setLineWidth(20)
        self.splitter.setMidLineWidth(20)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setHandleWidth(20)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.polarionTableView = QtWidgets.QTableView(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.polarionTableView.sizePolicy().hasHeightForWidth())
        self.polarionTableView.setSizePolicy(sizePolicy)
        self.polarionTableView.setMinimumSize(QtCore.QSize(100, 0))
        self.polarionTableView.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.polarionTableView.setStyleSheet("")
        self.polarionTableView.setAutoScroll(False)
        self.polarionTableView.setAlternatingRowColors(True)
        self.polarionTableView.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.polarionTableView.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.polarionTableView.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.polarionTableView.setShowGrid(True)
        self.polarionTableView.setSortingEnabled(True)
        self.polarionTableView.setObjectName("polarionTableView")
        self.logTableWidget = QtWidgets.QTableWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logTableWidget.sizePolicy().hasHeightForWidth())
        self.logTableWidget.setSizePolicy(sizePolicy)
        self.logTableWidget.setMinimumSize(QtCore.QSize(100, 0))
        self.logTableWidget.setStyleSheet("")
        self.logTableWidget.setAutoScroll(False)
        self.logTableWidget.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.logTableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.logTableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.logTableWidget.setObjectName("logTableWidget")
        self.logTableWidget.setColumnCount(0)
        self.logTableWidget.setRowCount(0)
        self.verticalLayout_8.addWidget(self.splitter)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_8.addLayout(self.verticalLayout_11)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.selectedEdit = QtWidgets.QLineEdit(self.tab_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectedEdit.sizePolicy().hasHeightForWidth())
        self.selectedEdit.setSizePolicy(sizePolicy)
        self.selectedEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.selectedEdit.setMaxLength(100)
        self.selectedEdit.setObjectName("selectedEdit")
        self.horizontalLayout_7.addWidget(self.selectedEdit)
        self.polarionRevisionLineEdit = QtWidgets.QLineEdit(self.tab_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.polarionRevisionLineEdit.sizePolicy().hasHeightForWidth())
        self.polarionRevisionLineEdit.setSizePolicy(sizePolicy)
        self.polarionRevisionLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.polarionRevisionLineEdit.setObjectName("polarionRevisionLineEdit")
        self.horizontalLayout_7.addWidget(self.polarionRevisionLineEdit)
        self.polarionOverViewLineEdit = QtWidgets.QLineEdit(self.tab_6)
        self.polarionOverViewLineEdit.setReadOnly(True)
        self.polarionOverViewLineEdit.setObjectName("polarionOverViewLineEdit")
        self.horizontalLayout_7.addWidget(self.polarionOverViewLineEdit)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.polarionLogEdit = QtWidgets.QPlainTextEdit(self.tab_6)
        self.polarionLogEdit.setMaximumSize(QtCore.QSize(16777215, 100))
        self.polarionLogEdit.setReadOnly(True)
        self.polarionLogEdit.setObjectName("polarionLogEdit")
        self.verticalLayout_8.addWidget(self.polarionLogEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/icon/polarion"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_6, icon16, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.sequenceFileEdit = QtWidgets.QLineEdit(self.tab_4)
        self.sequenceFileEdit.setClearButtonEnabled(True)
        self.sequenceFileEdit.setObjectName("sequenceFileEdit")
        self.horizontalLayout_5.addWidget(self.sequenceFileEdit)
        self.sequenceBrowseButton = QtWidgets.QToolButton(self.tab_4)
        self.sequenceBrowseButton.setObjectName("sequenceBrowseButton")
        self.horizontalLayout_5.addWidget(self.sequenceBrowseButton)
        self.sequenceConvertButton = QtWidgets.QPushButton(self.tab_4)
        self.sequenceConvertButton.setObjectName("sequenceConvertButton")
        self.horizontalLayout_5.addWidget(self.sequenceConvertButton)
        self.verticalLayout_16.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.sequenceEdit = QtWidgets.QPlainTextEdit(self.tab_4)
        self.sequenceEdit.setObjectName("sequenceEdit")
        self.horizontalLayout_12.addWidget(self.sequenceEdit)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem8)
        self.horizontalLayout_12.addLayout(self.verticalLayout_15)
        self.verticalLayout_16.addLayout(self.horizontalLayout_12)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/icon/automationDesk"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_4, icon17, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 5))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_3.addWidget(self.progressBar)
        self.bottombuttonsLayout = QtWidgets.QHBoxLayout()
        self.bottombuttonsLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.bottombuttonsLayout.setContentsMargins(0, -1, -1, -1)
        self.bottombuttonsLayout.setObjectName("bottombuttonsLayout")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottombuttonsLayout.addItem(spacerItem9)
        self.autorunSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.autorunSpinBox.sizePolicy().hasHeightForWidth())
        self.autorunSpinBox.setSizePolicy(sizePolicy)
        self.autorunSpinBox.setMinimumSize(QtCore.QSize(50, 0))
        self.autorunSpinBox.setMinimum(1)
        self.autorunSpinBox.setProperty("value", 45)
        self.autorunSpinBox.setObjectName("autorunSpinBox")
        self.bottombuttonsLayout.addWidget(self.autorunSpinBox)
        self.exitButton = QtWidgets.QToolButton(self.centralwidget)
        self.exitButton.setStyleSheet("QPushButton, QToolButton {\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(200, 133, 0);\n"
"}")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/icon/navigateNext"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitButton.setIcon(icon18)
        self.exitButton.setIconSize(QtCore.QSize(48, 48))
        self.exitButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.exitButton.setObjectName("exitButton")
        self.bottombuttonsLayout.addWidget(self.exitButton)
        self.verticalLayout_3.addLayout(self.bottombuttonsLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBar.setMovable(False)
        self.toolBar.setAllowedAreas(QtCore.Qt.AllToolBarAreas)
        self.toolBar.setOrientation(QtCore.Qt.Horizontal)
        self.toolBar.setIconSize(QtCore.QSize(24, 24))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setIcon(icon10)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setIcon(icon18)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/icon/info"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon19)
        self.actionAbout.setObjectName("actionAbout")
        self.actionOpenProfileFolder = QtWidgets.QAction(MainWindow)
        self.actionOpenProfileFolder.setIcon(icon2)
        self.actionOpenProfileFolder.setObjectName("actionOpenProfileFolder")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/icon/load"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoad.setIcon(icon20)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSaveAs = QtWidgets.QAction(MainWindow)
        self.actionSaveAs.setIcon(icon10)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionNew = QtWidgets.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/icon/new"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon21)
        self.actionNew.setObjectName("actionNew")
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionLoad)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionOpenProfileFolder)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSaveAs)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionAbout)
        self.variablePoolLabel.setBuddy(self.variablePoolEdit)
        self.csvReportLabel.setBuddy(self.csvReportEdit)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.exitButton.clicked.connect(self.actionExit.trigger)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.csvReportEdit, self.browseCsvReportBtn)
        MainWindow.setTabOrder(self.browseCsvReportBtn, self.variablePoolEdit)
        MainWindow.setTabOrder(self.variablePoolEdit, self.browseVariablePoolBtn)
        MainWindow.setTabOrder(self.browseVariablePoolBtn, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.variablePoolToolButton)
        MainWindow.setTabOrder(self.variablePoolToolButton, self.csvReportFolderToolButton)
        MainWindow.setTabOrder(self.csvReportFolderToolButton, self.logRadioBtn0)
        MainWindow.setTabOrder(self.logRadioBtn0, self.logRadioBtn1)
        MainWindow.setTabOrder(self.logRadioBtn1, self.logRadioBtn2)
        MainWindow.setTabOrder(self.logRadioBtn2, self.addSignalListView)
        MainWindow.setTabOrder(self.addSignalListView, self.addSignalEdit)
        MainWindow.setTabOrder(self.addSignalEdit, self.addSignalBtn)
        MainWindow.setTabOrder(self.addSignalBtn, self.removeSignalBtn)
        MainWindow.setTabOrder(self.removeSignalBtn, self.addDtcExEdit)
        MainWindow.setTabOrder(self.addDtcExEdit, self.removeDtcExBtn)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AutomationGUI"))
        self.testCaseExcelLabel_2.setText(_translate("MainWindow", "<html><head/><body><p>Polarion Excel File:</p></body></html>"))
        self.browseVariablePoolBtn.setToolTip(_translate("MainWindow", "Browse"))
        self.browseVariablePoolBtn.setText(_translate("MainWindow", "Browse"))
        self.browseCsvReportBtn.setToolTip(_translate("MainWindow", "Browse"))
        self.browseCsvReportBtn.setText(_translate("MainWindow", "Browse"))
        self.variablePoolLabel.setText(_translate("MainWindow", "VariablePool File:"))
        self.csvReportEdit.setPlaceholderText(_translate("MainWindow", "Specify the CSV report folder"))
        self.csvReportLabel.setText(_translate("MainWindow", "CSV Report Folder:"))
        self.variablePoolEdit.setPlaceholderText(_translate("MainWindow", "Specify the variable pool text file"))
        self.polarionExcelEdit.setPlaceholderText(_translate("MainWindow", "Specify Polarion test case excel file"))
        self.variablePoolToolButton.setToolTip(_translate("MainWindow", "Open Folder + File"))
        self.polarionExcelToolButton.setToolTip(_translate("MainWindow", "Open Folder + File"))
        self.browsePolarionExcelBtn.setToolTip(_translate("MainWindow", "Browse"))
        self.browsePolarionExcelBtn.setText(_translate("MainWindow", "Browse"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Tool Options"))
        self.updateVariablePoolCheckBox.setText(_translate("MainWindow", "Update VariablePool in AutomationDesk"))
        self.autorunCheckBox.setText(_translate("MainWindow", "Autorun"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Runtime Options"))
        self.versionCheckBox.setText(_translate("MainWindow", "Include HW && SW Version"))
        self.callFunctionDebugCheckbox.setText(_translate("MainWindow", "Show Call Function Messages"))
        self.dtcExCheckBox.setText(_translate("MainWindow", "Enable DTC Exception(s)"))
        self.pauseCheckbox.setText(_translate("MainWindow", "Pause Enable"))
        self.pauseStepSpinbox.setPrefix(_translate("MainWindow", "step# "))
        self.printStepsInOutputCheckbox.setText(_translate("MainWindow", "Steps in Output"))
        self.maxPrintsInOutputSpinbox.setSuffix(_translate("MainWindow", " testcases"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Versions"))
        self.versionAddButton.setText(_translate("MainWindow", "Add Module"))
        self.versionRemoveButton.setText(_translate("MainWindow", "Remove Module"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Settings"))
        self.groupBox.setTitle(_translate("MainWindow", "Logging Mode"))
        self.logRadioBtn0.setText(_translate("MainWindow", "Execution Only (Default)"))
        self.logRadioBtn1.setText(_translate("MainWindow", "Execution with Filtered Logging"))
        self.logRadioBtn2.setText(_translate("MainWindow", "Execution with Full Logging\n"
"and Additional Signals"))
        self.addSignalGroupBox.setTitle(_translate("MainWindow", "Additional Signal List"))
        self.addSignalBtn.setText(_translate("MainWindow", "Add"))
        self.removeSignalBtn.setText(_translate("MainWindow", "Remove"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Logging"))
        self.dtcExGroupBox.setTitle(_translate("MainWindow", "DTC Exception List"))
        self.addDtcExEdit.setPlaceholderText(_translate("MainWindow", "Enter DTC exception in hex here..."))
        self.addDtcExBtn.setText(_translate("MainWindow", "Add DTC"))
        self.removeDtcExBtn.setText(_translate("MainWindow", "Remove DTC"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "DTC"))
        self.polarionReadExcelButton.setToolTip(_translate("MainWindow", "Read Polarion excel file"))
        self.polarionReadExcelButton.setText(_translate("MainWindow", "Read"))
        self.polarionSaveExcelButton.setToolTip(_translate("MainWindow", "Save polarion excel file"))
        self.polarionSaveExcelButton.setText(_translate("MainWindow", "Save"))
        self.polarionUpdatePassedButton.setToolTip(_translate("MainWindow", "Update excel with Passed verdicts only"))
        self.polarionUpdatePassedButton.setText(_translate("MainWindow", "Update Passed Verdicts Only"))
        self.polarionUpdateAllButton.setToolTip(_translate("MainWindow", "Update excel with All verdicts"))
        self.polarionUpdateAllButton.setText(_translate("MainWindow", "Update All Verdicts"))
        self.polarionUpdateRevisionButton.setToolTip(_translate("MainWindow", "Update excel with current revision number"))
        self.polarionUpdateRevisionButton.setText(_translate("MainWindow", "Revision"))
        self.updateStepsButton.setToolTip(_translate("MainWindow", "Push updated steps to Polarion server"))
        self.updateStepsButton.setText(_translate("MainWindow", "Steps"))
        self.updateHyperlinksButton.setToolTip(_translate("MainWindow", "Pull hyperlinks from Polarion server"))
        self.updateHyperlinksButton.setText(_translate("MainWindow", "Hyperlinks"))
        self.titleEdit.setPlaceholderText(_translate("MainWindow", "Title"))
        self.descriptionEdit.setPlaceholderText(_translate("MainWindow", "Description"))
        self.polarionRevisionLineEdit.setPlaceholderText(_translate("MainWindow", "Revision number"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Polarion"))
        self.sequenceFileEdit.setPlaceholderText(_translate("MainWindow", "Browse for Sequence file..."))
        self.sequenceBrowseButton.setText(_translate("MainWindow", "..."))
        self.sequenceConvertButton.setText(_translate("MainWindow", "Convert"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Sequence Converter"))
        self.progressBar.setFormat(_translate("MainWindow", "%p%"))
        self.exitButton.setText(_translate("MainWindow", "Continue"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionOpenProfileFolder.setText(_translate("MainWindow", "Open Profile Folder"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionLoad.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSaveAs.setText(_translate("MainWindow", "Save As"))
        self.actionNew.setText(_translate("MainWindow", "New"))

import AutomationGUI_rc
